services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5

  redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379"
    mem_limit: 256m
    mem_reservation: 128m
    cpus: 0.25

  web:
    build: .
    image: payment_system
    ports:
      - "3000:80"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      REDIS_URL: ${REDIS_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - postgres
      - redis
    mem_limit: 1g
    mem_reservation: 512m
    cpus: 1.0

  sidekiq:
    image: payment_system
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: ${RAILS_ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      REDIS_URL: ${REDIS_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - web
    mem_limit: 1g
    mem_reservation: 512m
    cpus: 0.75 # Bump this up for heavier workloads

volumes:
  pgdata:
